Algoritmo "tabuada_enquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/05/2022
Var

   i:inteiro
   valor:inteiro

Inicio


   escreva("Digite o valor para a tabuada: ")
   leia(valor)

   i <- 1

   enquanto i <= 10 faca
      escreval(valor, " x " , i, " = ", valor * i)
      i <- i + 1

   fimenquanto


Fimalgoritmo