Algoritmo "somanvalores"
// Enquanto o valor inserido for diferente de 0, continuar somando.


Var

   i:inteiro
   valor:inteiro
   soma:inteiro

Inicio


   escreva("Digite um valor para a soma: ")
   leia(valor)

   enquanto valor <> 0 faca

      soma <- soma + valor
      escreva("Digite um valor para a soma: ")
      leia(valor)

   fimenquanto

   escreva("A soma dos valores é = ", soma)




Fimalgoritmo