Algoritmo "ex02"
// Ex02. Escreva um algoritmo para ler o seu nome e sua idade
// e escreva como saída Bem vindo!! "nome digitado",
// você tem "idade digitada".


Var
nome: caracter
idade: inteiro

Inicio
escreva("Digite o seu nome: ")
leia(nome)
escreva("Digite sua idade: ")
leia(idade)

escreval() // quebra de linha
escreva("Bem vindo! ", nome, ", você tem:", idade, " anos.")
escreval()

Fimalgoritmo