Algoritmo "ex2_procedimento"

procedimento calculos(p1,p2:real)

var
   soma,subtracao:real

inicio

   soma <- p1 + p2
   subtracao <- p1 - p2

   escreval("A soma dos valores = ", soma)
   escreval("A subtração dos valores = ", subtracao)
   escreval("=============================================")

fimprocedimento


Var



Inicio

   // pode chmar quantas vezes quiser

   calculos(10,5) // tem que especificar os valores
   calculos(20,15) // tem que especificar os valores
   calculos(50,20) // tem que especificar os valores


Fimalgoritmo

// procedimento calculos(p1,p2:real)

// inicio

//   soma <- p1 + p2
//   subtracao <- p1 - p2
//   escreval("A soma do valores = ", soma)
//   escreval("A subtração dos valores = ", subtracao)
// fimprocedimento

// Var
//   soma,subtracao:real
//   v1,v2:real
// Inicio

//   leia(v1)
//   leia(v2)

//   calculos(v1,v2)

// Fimalgoritmo
