Algoritmo "ex_matriz"
// Disciplina   : [Linguagem e Lógica de Programação]

Var

   matrizA:vetor[1..2,1..2] de inteiro
   l, c:inteiro  // l = linha e c = coluna

Inicio


   para l de 1 ate 2 faca
      // llinha (para cada linha será lida 02 colunas

      para c de 1 ate 2 faca
         // coluna

         leia(matrizA[l,c])

            fimpara
         escreval("")
       fimpara
       
       // VER CÓDIGO COMPLETO WORD


Fimalgoritmo